AllCops:
  NewCops: enable

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Layout/EndOfLine:
   Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50
 
Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*_spec.rb"
    
  
