AllCops:
  NewCops: enable

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Layout/EndOfLine:
   Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
